### ISSUE TITLE
Domain registration and setup

### ISSUE THREAD

**Issue by sdmcraft** [srshrm/dx-portal#5]
This task is logged for setting up a domain for the dx-portal. 
[Please check the process here](https://inside.corp.adobe.com/search.html#q=domain%20name&t=intranet)

**Comment by srshrm** [comment]
@sdmcraft Do we require new domain or just a new subdomain with existing `adobe.com` domain?
For example: `dx.adobe.com` probably could be host name.

**Comment by RitwikSrivastava** [comment]
Even I think dx.adobe.com could be our hostname. 

I was going through the docs to provision new domains and subdomains. 
So new domains can be registered via https://dns.corp.adobe.com/#/request/domain/new 
But if we need to request a Subdomain, that can be done via IT Support Form.

**Comment by sdmcraft** [comment]
Yes, some suggestions
```
dx.adobe.com
dxportal.adobe.com
digitalexperience.adobe.com
```

**Comment by sdmcraft** [comment]
Being tracked here https://github.com/adobe/dx-portal/issues/10
